@EventTicketingSystem.Api_HostAddress = https://localhost:7299

POST {{EventTicketingSystem.Api_HostAddress}}/api/venues
Content-Type: application/json

{
  "name": "Tbilisi Arena123",
  "address": "Tbilisi123"
}

###

GET {{EventTicketingSystem.Api_HostAddress}}/api/venues


###

GET {{EventTicketingSystem.Api_HostAddress}}/api/venues/13


###


POST {{EventTicketingSystem.Api_HostAddress}}/api/venues/12/seats
Content-Type: application/json

{
  "Section" : "ABCfF",
  "Row": "Row 4fsf32",
  "Number": 12 
}

###

GET {{EventTicketingSystem.Api_HostAddress}}/api/venues/16/seats

###


POST {{EventTicketingSystem.Api_HostAddress}}/api/events
Content-Type: application/json

{
  "name" : "SXVA123",
  "description": "SXVA",
  "startDate": "2026-08-23T12:53:00Z",
  "endDate": "2026-09-23T12:53:00Z",
  "venueId": 12
}

###

GET {{EventTicketingSystem.Api_HostAddress}}/api/events

###

GET {{EventTicketingSystem.Api_HostAddress}}/api/events/18

###


## Venue Id should be same for seat and event
POST {{EventTicketingSystem.Api_HostAddress}}/api/events/18/seats
Content-Type: application/json

{
  "SeatId" : "15",
  "Price": "1500"
}

###

GET {{EventTicketingSystem.Api_HostAddress}}/api/events/18/seats

###


POST {{EventTicketingSystem.Api_HostAddress}}/api/reservations
Content-Type: application/json

{
  "EventSeatId" : 3,
  "UserId": 1
}

###


POST {{EventTicketingSystem.Api_HostAddress}}/api/bookings
Content-Type: application/json

{
  "ReservationId" : 13
}

###

