@EventTicketingSystem.Api_HostAddress = https://localhost:7299

POST {{EventTicketingSystem.Api_HostAddress}}/api/venues
Content-Type: application/json

{
  "name": "Tbilisi Are Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arena Arenana",
  "address": "Tbilisi"
}

###